codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "0"

  status:
    project: yes
    patch: yes
    changes: no

  ignore:
    -Applications/Xcode.app/*
    -KeepUpTests/*
    -KeepUp/*ViewController.*
    -KeepUp/AppDelegate.swift
    -KeepUp/*.storyboard


parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
